package acm.program;

public interface ProgramStartupFlags {
	String SPL_AUTOGRADER_MODE = "SPL_AUTOGRADER_MODE";
	String SPL_CONSOLE_FONTSIZE = "SPL_CONSOLE_FONTSIZE";
	String SPL_CONSOLE_WIDTH = "SPL_CONSOLE_WIDTH";
	String SPL_CONSOLE_HEIGHT = "SPL_CONSOLE_HEIGHT";
	String SPL_CONSOLE_X = "SPL_CONSOLE_X";
	String SPL_CONSOLE_Y = "SPL_CONSOLE_Y";
	String SPL_CONSOLE_ECHO = "SPL_CONSOLE_ECHO";
	String SPL_CONSOLE_EXIT_ON_CLOSE = "SPL_CONSOLE_EXIT_ON_CLOSE";
	String SPL_CONSOLE_LOCATION_SAVED = "SPL_CONSOLE_LOCATION_SAVED";
}
