#!/bin/bash
OUTDIR=cppdoc/dist
LIBDIR=lib/StanfordCPPLib
AUTOGRADERDIR=autograder
AUTOGRADERLIBZIPFILE=$OUTDIR/StanfordCPPLibAutograder.zip
PROFILE=StanfordCPPLib_QtCreatorProject/stanfordcpplib.pro

echo "This script prepares ZIPs of the Stanford C++ library"
echo "(autograder) for distribution and posting on the web."
echo "====================================================="
echo "Building $AUTOGRADERLIBZIPFILE ..."
rm $AUTOGRADERLIBZIPFILE 2>/dev/null
zip -rq $AUTOGRADERLIBZIPFILE $AUTOGRADERDIR/

AUTOGRADEREMPTYPROJECTNAME=autograder-empty-project
EMPTYPROJECTZIPFILE=$OUTDIR/$AUTOGRADEREMPTYPROJECTNAME.zip
echo "Building $EMPTYPROJECTZIPFILE ..."
cp -f $PROFILE $AUTOGRADEREMPTYPROJECTNAME/$AUTOGRADEREMPTYPROJECTNAME.pro
rm -rf $AUTOGRADEREMPTYPROJECTNAME/$LIBDIR
rm -rf $AUTOGRADEREMPTYPROJECTNAME/$LIBDIR
mkdir $AUTOGRADEREMPTYPROJECTNAME/$LIBDIR
mkdir $AUTOGRADEREMPTYPROJECTNAME/$LIBDIR/$AUTOGRADERDIR
cp -r StanfordCPPLib/* $AUTOGRADEREMPTYPROJECTNAME/$LIBDIR
#mkdir $AUTOGRADEREMPTYPROJECTNAME/$LIBDIR/$AUTOGRADERDIR
cp -r $AUTOGRADERDIR/*.h $AUTOGRADEREMPTYPROJECTNAME/$LIBDIR/$AUTOGRADERDIR
./pack-lib-into-single-cpp-file.sh $AUTOGRADEREMPTYPROJECTNAME
./pack-autograder-lib-into-single-cpp-file.sh $AUTOGRADEREMPTYPROJECTNAME
rm $EMPTYPROJECTZIPFILE 2>/dev/null
zip -rq $EMPTYPROJECTZIPFILE $AUTOGRADEREMPTYPROJECTNAME/
cp -f $AUTOGRADEREMPTYPROJECTNAME/$AUTOGRADEREMPTYPROJECTNAME.pro $OUTDIR

echo "Done."
